name: Mirror Brave Browser Releases

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create/delete releases
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Latest Brave Release Info
        id: brave_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest release tag from the official Brave repo
          LATEST_TAG=$(gh release view --repo brave/brave-browser --json tagName --template '{{.tagName}}')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          
          # Check if this tag already exists in YOUR repo
          EXISTS=$(gh release view $LATEST_TAG >/dev/null 2>&1 && echo "true" || echo "false")
          echo "EXISTS=$EXISTS" >> $GITHUB_ENV

      - name: Mirror Release
        if: env.EXISTS == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "New version found: ${{ env.LATEST_TAG }}. Mirroring..."
          
          # 1. Download only .dmg assets from Brave
          gh release download ${{ env.LATEST_TAG }} \
            --repo brave/brave-browser \
            --pattern "*.dmg" \
            --dir ./downloads

          # 2. Create the release in your repo
          gh release create ${{ env.LATEST_TAG }} \
            ./downloads/*.dmg \
            --title "Brave Browser ${{ env.LATEST_TAG }}" \
            --notes "Automated mirror of Brave Browser macOS release ${{ env.LATEST_TAG }}."

      - name: Cleanup Old Releases (Keep N-1)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Cleaning up old releases, keeping only the 2 most recent..."
          
          # List all releases, skip the first 2 (n and n-1), and delete the rest
          RELEASES_TO_DELETE=$(gh release list --limit 100 | tail -n +3 | awk '{print $1}')
          
          for TAG in $RELEASES_TO_DELETE; do
            echo "Deleting old release: $TAG"
            gh release delete $TAG --yes --cleanup-tag
          done
          
      - name: Calculate Hashes and Update Cask
        env:
          TAP_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
        run: |
          # 1. Get the hashes from the downloaded DMGs
          ARM_SHA=$(shasum -a 256 Brave-Browser-arm64.dmg | awk '{print $1}')
          INTEL_SHA=$(shasum -a 256 Brave-Browser-x64.dmg | awk '{print $1}')
          VERSION=${{ env.BRAVE_VERSION }} # Ensure your workflow sets this variable

          # 2. Clone the Tap repository
          git clone https://x-access-token:${TAP_TOKEN}@github.com/YOUR_USER/courage-tap.git tap-repo
          cd tap-repo/Casks

          # 3. Update the courageux.rb file using sed
          # Update version
          sed -i '' "s/version \".*\"/version \"$VERSION\"/" courageux.rb
          # Update ARM SHA
          sed -i '' "s/arm:[[:space:]]*\".*\"/arm:   \"$ARM_SHA\"/" courageux.rb
          # Update Intel SHA
          sed -i '' "s/intel:[[:space:]]*\".*\"/intel: \"$INTEL_SHA\"/" courageux.rb

          # 4. Commit and Push
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add courageux.rb
          git commit -m "Update courageux to $VERSION"
          git push
